import os
import httpx
import json
from datetime import datetime, timezone, timedelta
from dotenv import load_dotenv

load_dotenv()

ELASTIC_API_KEY = os.getenv("ELASTIC_API_KEY")
AGENT_ID = os.getenv("ELASTIC_AGENT_ID", "afrigov-sentinel")
KIBANA_URL = os.getenv("KIBANA_URL")
AGENT_ENDPOINT = f"{KIBANA_URL}/api/agent_builder/converse"


async def generate_weekly_report(stats: dict, incidents: list, escalations: list) -> str:
    """Ask the Agent Builder to generate a structured weekly report."""

    # Build context summary
    by_region = {}
    by_service = {}
    critical_list = []

    for inc in incidents:
        r = inc.get("region", "Unknown")
        s = inc.get("service", "Unknown")
        by_region[r] = by_region.get(r, 0) + 1
        by_service[s] = by_service.get(s, 0) + 1
        if inc.get("severity", 0) >= 4:
            critical_list.append(f"- {inc.get('ville')}: {inc.get('description','')[:80]} (sev {inc.get('severity')})")

    region_summary = "\n".join([f"  - {k}: {v} incidents" for k, v in sorted(by_region.items(), key=lambda x: -x[1])])
    service_summary = "\n".join([f"  - {k}: {v} incidents" for k, v in sorted(by_service.items(), key=lambda x: -x[1])[:5]])
    critical_summary = "\n".join(critical_list[:8]) if critical_list else "  None this week."

    week_start = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%B %d, %Y")
    week_end = datetime.now(timezone.utc).strftime("%B %d, %Y")

    prompt = f"""You are AfriGov Sentinel's reporting engine. Generate a formal weekly governance report in English for Togo authorities.

WEEK: {week_start} → {week_end}

RAW DATA:
- Total incidents this week: {stats.get('total_incidents', 0)}
- Average severity: {stats.get('avg_severity', 0)}
- Active escalations: {len(escalations)}

By region:
{region_summary}

Top affected services:
{service_summary}

Critical incidents (severity 4-5):
{critical_summary}

Generate a professional weekly report with these exact sections:
1. Executive Summary (3 sentences max)
2. Key Findings (3-4 bullet points with data)
3. Critical Incidents Requiring Immediate Action
4. Regional Analysis
5. Recommendations for Next Week (3 actionable items)

Be concise, data-driven, and authoritative. Write as if this will be read by a government minister."""

    headers = {
        "Authorization": f"ApiKey {ELASTIC_API_KEY}",
        "Content-Type": "application/json",
        "kbn-xsrf": "true",
    }
    payload = {"input": prompt, "agent_id": AGENT_ID}

    try:
        async with httpx.AsyncClient(timeout=120.0) as client:
            resp = await client.post(AGENT_ENDPOINT, headers=headers, json=payload)
            resp.raise_for_status()
            data = resp.json()

        response_obj = data.get("response", {})
        if isinstance(response_obj, dict):
            content = response_obj.get("message", "")
        else:
            content = str(response_obj)

        # Clean markdown code blocks if any
        if "```" in content:
            parts = content.split("```")
            content = parts[0] if parts[0].strip() else (parts[2] if len(parts) > 2 else content)

        return content.strip()

    except Exception as e:
        print(f"[ReportClient] Error: {e}")
        return _fallback_report(stats, incidents, escalations, week_start, week_end)


def _fallback_report(stats, incidents, escalations, week_start, week_end):
    return f"""# AfriGov Sentinel — Weekly Report
**Period:** {week_start} → {week_end}

## Executive Summary
AfriGov Sentinel recorded {stats.get('total_incidents', 0)} incidents this week across Togo with an average severity of {stats.get('avg_severity', 'N/A')}. There are currently {len(escalations)} active critical escalations requiring immediate authority action.

## Key Findings
- Total incidents reported: {stats.get('total_incidents', 0)}
- Active escalations: {len(escalations)}
- Average severity score: {stats.get('avg_severity', 'N/A')} / 5.0

## Recommendations
1. Address all active critical escalations within 24 hours
2. Increase monitoring in regions with highest incident density
3. Conduct service audits for most-affected departments

*Generated by AfriGov Sentinel AI Agent*"""